version: '2'

services:
  verdaccio:
    image: verdaccio/verdaccio:3
    container_name: verdaccio-3-docker-local-storage-vol
    ports:
      - "4873:4873"
    volumes:
        - "./storage:/verdaccio/storage"
        - "./conf:/verdaccio/conf"